# Generated by Django 5.0.1 on 2024-01-19 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(choices=[('Tecnologia e Inovação', 'Tecnologia e Inovação'), ('Ciência e Descobertas', 'Ciência e Descobertas'), ('Saúde e Bem-estar', 'Saúde e Bem-estar'), ('Educação e Aprendizado', 'Educação e Aprendizado'), ('Meio Ambiente e Sustentabilidade', 'Meio Ambiente e Sustentabilidade'), ('Arte e Cultura', 'Arte e Cultura'), ('Viagens e Aventuras', 'Viagens e Aventuras'), ('Filmes, Séries e Entretenimento', 'Filmes, Séries e Entretenimento'), ('Esportes e Atividades Físicas', 'Esportes e Atividades Físicas'), ('Negócios e Empreendedorismo', 'Negócios e Empreendedorismo'), ('Finanças Pessoais e Investimentos', 'Finanças Pessoais e Investimentos'), ('Relacionamentos e Vida Social', 'Relacionamentos e Vida Social'), ('Política e Atualidades', 'Política e Atualidades'), ('Moda e Estilo', 'Moda e Estilo'), ('Culinária e Gastronomia', 'Culinária e Gastronomia'), ('Hobbies e Passatempos', 'Hobbies e Passatempos'), ('Dicas de Livros e Leitura', 'Dicas de Livros e Leitura'), ('Automóveis e Tecnologia Automotiva', 'Automóveis e Tecnologia Automotiva'), ('Parentalidade e Família', 'Parentalidade e Família'), ('Fotografia e Arte Visual', 'Fotografia e Arte Visual')], max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('votos_positivos', models.IntegerField(default=0)),
                ('votos_negativos', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topico', models.ManyToManyField(blank=True, default=None, null=True, to='topico.topico')),
            ],
        ),
    ]
