# Generated by Django 5.0.1 on 2024-01-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0002_alter_comentario_topico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='votos_negativos',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='votos_positivos',
        ),
        migrations.AddField(
            model_name='comentario',
            name='votos_negativos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='votos_positivos',
            field=models.IntegerField(default=0),
        ),
    ]
