# Generated by Django 5.0.1 on 2024-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0003_remove_topico_votos_negativos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='topico',
            field=models.ManyToManyField(to='topico.topico'),
        ),
    ]
